"use client";

import {
  Copy,
  ExternalLink,
  RefreshCw,
  Check,
  AlertCircle,
} from "lucide-react";
import { useState, useEffect } from "react";
import type { FC } from "react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { useMessageVerification } from "@/hooks/use-message-verification";
import { useAttestationStore } from "@/state/attestation";
import { useMessageVerificationStore } from "@/state/message-verification";

interface MessageVerificationDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  messageId: string | null;
}

export const MessageVerificationDialog: FC<MessageVerificationDialogProps> = ({
  open,
  onOpenChange,
  messageId,
}) => {
  const { verifyMessage } = useMessageVerification();
  const attestationData = useAttestationStore((state) => state.attestationData);
  const [copiedField, setCopiedField] = useState<string | null>(null);

  const verificationState = useMessageVerificationStore((state) =>
    messageId ? state.verifications.get(messageId) : undefined,
  );

  const { isVerifying, signatureData, error } = verificationState || {
    isVerifying: false,
    signatureData: null,
    error: null,
  };

  useEffect(() => {
    if (open && messageId && !signatureData && !isVerifying) {
      verifyMessage(messageId);
    }
  }, [open, messageId, signatureData, isVerifying, verifyMessage]);

  const handleCopy = async (text: string, fieldId: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(fieldId);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
    }
  };

  const renderField = (label: string, value: string, fieldId: string) => (
    <div className="space-y-2">
      <label className="block text-sm font-medium text-foreground">
        {label}
      </label>
      <div className="relative">
        <div className="bg-muted p-3 rounded-md font-mono text-xs break-all max-h-32 overflow-y-auto">
          {value}
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={() => handleCopy(value, fieldId)}
          className="absolute bottom-2 right-2 h-6 px-2 text-xs"
        >
          <Copy className="h-2.5 w-2.5 mr-1" />
          {copiedField === fieldId ? "Copied!" : "Copy"}
        </Button>
      </div>
    </div>
  );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            Message Verification
          </DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-4">
          {/* Status */}
          <div
            className={cn(
              "flex items-center gap-3 p-4 rounded-lg border",
              isVerifying
                ? "bg-muted border-border"
                : error
                  ? "bg-red-50 border-red-200"
                  : signatureData
                    ? "bg-green-50 border-green-200"
                    : "bg-muted border-border",
            )}
          >
            {isVerifying ? (
              <RefreshCw className="h-5 w-5 text-muted-foreground animate-spin flex-shrink-0" />
            ) : error ? (
              <AlertCircle className="h-5 w-5 text-red-600 flex-shrink-0" />
            ) : signatureData ? (
              <Check className="h-5 w-5 text-green-600 flex-shrink-0" />
            ) : null}

            <span
              className={cn(
                "font-medium text-sm",
                isVerifying
                  ? "text-foreground"
                  : error
                    ? "text-red-800"
                    : signatureData
                      ? "text-green-800"
                      : "text-foreground",
              )}
            >
              {isVerifying
                ? "Verifying message..."
                : error
                  ? "Message verification failed"
                  : signatureData
                    ? "Message verified"
                    : "Ready to verify"}
            </span>
          </div>

          {/* Description */}
          <div className="text-sm text-muted-foreground leading-relaxed">
            <p>
              Verify messages generated by LLMs running in TEE. Each response is
              signed within TEE to guarantee authenticity.
            </p>
            <p className="mt-2">
              <a
                href="https://docs.redpill.ai/confidential-ai-inference/get-started#verify-signature"
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs text-primary hover:text-primary/80 flex items-center gap-1"
              >
                <ExternalLink className="h-3 w-3 flex-shrink-0" />
                Learn more about message verification
              </a>
            </p>
          </div>

          {/* Error Message */}
          {error && (
            <div className="text-sm text-red-600 bg-red-50 p-3 rounded-md">
              {error}
            </div>
          )}

          {/* Signature Details */}
          {signatureData && (
            <div className="space-y-4">
              <h3 className="font-medium text-foreground">Signature Details</h3>

              {renderField(
                "Signing Address",
                attestationData?.signing_address || "-",
                "signing-address",
              )}
              {renderField("Message", signatureData.text, "message")}
              {renderField("Signature", signatureData.signature, "signature")}
              {renderField(
                "Algorithm",
                signatureData.signing_algo,
                "algorithm",
              )}

              <div className="flex items-center gap-2 pt-2">
                <a
                  href="https://etherscan.io/verifiedSignatures"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-primary hover:text-primary/80 flex items-center gap-1"
                >
                  <ExternalLink className="h-3 w-3 flex-shrink-0" />
                  Verify the signature on Etherscan
                </a>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};
